### PR TITLE
Format Intro Article as a LaTex Article

### PR DESCRIPTION
**Pull request by juanitorduz**
We want to refactor the [Google Doc Intro Article](https://docs.google.com/document/d/1ozj7LD5GwjlyVTYF2IWIRY-vGrq8-btY/edit) as a latex and pdf file.

### CODE REVIEW

**Comment by juanitorduz** [comment]
We can generate a nicer version of Fig 1 as follows:
```python
x_red = np.zeros(10)
x_blue = np.zeros(10)
t = np.arange(1, 11)

x_red[3] = 1
x_red[7] = 1

x_blue[4] = 1
x_blue[7] = 1

fig, ax = plt.subplots(figsize=(8, 6))
sns.lineplot(x=t, y=x_red, marker='o', color='red', label='observed', ax=ax)
sns.lineplot(x=t, y=x_blue, marker='o', color='blue', label='real', ax=ax)
ax.lines[0].set_linestyle('dashed')
ax.lines[1].set_linestyle("dashdot")
ax.legend(loc='center left', bbox_to_anchor=(1, 0.5))
ax.set(xlabel='t', ylabel='effect size');
plt.savefig(f'obs_real.png', dpi=200,  bbox_inches='tight');
```
image

**Comment by aaron1rcl** [comment]
Looking good!

**Comment by juanitorduz** [comment]
Hey! I added the `png` images and added them to the `pdf`. Note how I referenced the figures on the `tex`. We can re-arrange the figure distribution at the end.

**Comment by juanitorduz** [comment]
@aaron1rcl there are conflicts with a notebook and an image. Which one is the version you want to keep?

**Pull request merged**
